[PHP]
; Общие настройки
engine = On
short_open_tag = Off
asp_tags = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
unserialize_callback_func =
serialize_precision = -1
disable_functions =
disable_classes =
zend.enable_gc = On

; Обработка ошибок
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /var/log/php_errors.log
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
html_errors = On

; Ресурсы
max_execution_time = 30
max_input_time = 60
memory_limit = 256M

; Загрузка файлов
file_uploads = On
upload_max_filesize = 2M
max_file_uploads = 20
upload_tmp_dir = /tmp

; POST-запросы
post_max_size = 8M
max_input_vars = 1000

; Сессии
session.save_handler = files
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_secure = 0
session.cookie_httponly = 1
session.gc_maxlifetime = 1440
session.gc_probability = 1
session.gc_divisor = 1000

; Временные директории
sys_temp_dir = "/tmp"


; Другие важные настройки
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60